#-----------------------------------------------------------------------
# Matlab lib and binaries
#-----------------------------------------------------------------------

# Name of the library we will create

LIBSO_PREFIX  = lib$(PROJ_PREFIX)Matlab

MATLAB = true

# And include the generic Makefile

include $(TOP)/Makefile_generic

