#-----------------------------------------------------------------------
# Util lib
#-----------------------------------------------------------------------

# Name of the library we will create

LIBSO_PREFIX  = lib$(PROJ_PREFIX)Util

# Finally, include the generic Makefile

include $(TOP)/Makefile_generic

