#-----------------------------------------------------------------------
# Python lib (if any) and binaries
#-----------------------------------------------------------------------

# Name of the library we will create

LIBSO_PREFIX  = lib$(PROJ_PREFIX)Python

PYTHON = true

# And include the generic Makefile

include $(TOP)/Makefile_generic

