#-----------------------------------------------------------------------
# Models lib
#-----------------------------------------------------------------------

# Name of the library we will create

LIBSO_PREFIX  = lib$(PROJ_PREFIX)Models

# Finally, include the generic Makefile

CCFLAGS += -DFFTW_ENABLE_FLOAT -I$(TOP)/fftwc_src -I$(TOP)/fftwr_src

include $(TOP)/Makefile_generic

